name       : openlp
version    : 2.4.6
release    : 2
source     :
    - https://get.openlp.org/2.4.6/OpenLP-2.4.6.tar.gz : f63dcf5f1f8a8199bf55e806b44066ad920d26c9cf67ae432eb8cdd1e761fc30
license    : GPL-2.0
component  : multimedia.graphics
summary    : OpenLP is a feature rich open-source church presentation platform
description: |
    OpenLP is a feature rich open-source church presentation platform
builddeps  :
    - qt5-tools
rundeps    :
    - python3-qt5
    - pyenchant
    - python-alembic
    - python-beautifulsoup4
    - python-chardet
    - python-lxml
    - pyxdg
build      : |
    %python3_setup
install    : |
    %python3_install

    # Fix the binary name so that python will run
    mv $installdir/usr/bin/openlp.py $installdir/usr/bin/openlp

    # Assets and .desktop
    install -D -m 00644 resources/openlp.desktop $installdir/usr/share/applications/openlp.desktop
    for px in 16 32 48 64 128 256; do
        install -D -m 00644 resources/images/openlp-logo-${px}x${px}.png $installdir/usr/share/icons/hicolor/${px}x${px}/apps/openlp.png
    done
    install -D -m 00644 resources/images/openlp-logo.svg $installdir/usr/share/icons/hicolor/scalable/apps/openlp.svg

    # Translations
    install -d $installdir/usr/share/openlp/i18n
    cd resources/i18n
    for t in *.ts; do
        lconvert -i $t -o $installdir/usr/share/openlp/i18n/${t%%ts}qm
    done

    # Remove the tests
    rm -rf /usr/lib/python3.5/site-packages/tests
